### ISSUE TITLE
[BUG] App closes upon creating profile

### ISSUE THREAD

**Issue by ThePhaseCat** [trainb0y1/PyMultibound#4]
**Describe the bug**
When I create a new profile, the app completely closes. Upon opening the app and selecting this new profile, it does nothing

**To Reproduce**
1. Open gui.py
2. Create new profile (crashes)
3. Attempt to run Starbound via the gui

**Expected behavior**
A profile should be created with no crashes, and it should correctly open Starbound upon clicking

**Other Information:**
 - OS: Windows 10
 - (There are two logs, one is when I create the profile, the other is attempting to run Starbound)
 - Latest Starbound log unavabile because I don't even think the game starts

(i'm pretty sure it's crashing because my Starbound is installed somewhere else and the app doesn't know this, so it's unable to open Starbound)

[PyMultibound(log1).log](https://github.com/trainb0y1/PyMultibound/files/8712415/PyMultibound.log1.log)
[PyMultibound(log2).log](https://github.com/trainb0y1/PyMultibound/files/8712416/PyMultibound.log2.log)

**Comment by trainb0y1** [comment]
Yeah it only checks the default Starbound install location.

Will make a settings menu to set file paths, soon:tm:

**Comment by trainb0y1** [comment]
Fixed with https://github.com/trainb0y1/PyMultibound/commit/1713ba0cd9a93c02313711ec120e2ca846262676
Not the best solution, as there is no way to set paths in the GUI, but it works.

Will create new release soon.

**Comment by trainb0y1** [comment]
https://github.com/trainb0y1/PyMultibound/releases/tag/v1.1.0
